export const workflowSkillsPackageMetadata = {
  packageName: '@repo/workflow-skills',
  publishable: false,
  stagedSkillNames: [
    'claude',
    'review',
    'autoplan',
    'investigate',
    'health',
    'plan-eng-review',
    'plan-ceo-review',
    'plan-design-review',
    'plan-devex-review',
    'browse',
    'qa-only',
    'qa',
    'devex-review',
    'design-review',
    'codex',
    'opencode-go',
    'deepseek',
    'glm',
    'kimi',
    'minimax',
    'mimo',
    'qwen',
    'hy3',
  ],
  provenanceRequired: true,
} as const
