import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { tmpdir } from 'node:os'

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { auditBlueprintReadmeDrift } from './blueprint-readme-drift.js'

let cwd: string

function writeBlueprint(relativePath: string): void {
  const fullPath = path.join(cwd, 'blueprints', relativePath)
  mkdirSync(path.dirname(fullPath), { recursive: true })
  writeFileSync(
    fullPath,
    [
      '---',
      'type: blueprint',
      'title: Example',
      'owner: test',
      `status: ${relativePath.split(path.sep)[0]}`,
      'complexity: S',
      "created: '2026-06-04'",
      "last_updated: '2026-06-04'",
      '---',
      '',
      '# Example',
      '',
      '#### Task 1.1: Example',
      '',
      '**Status:** todo',
      '',
      '**Acceptance:**',
      '',
      '- [ ] Example',
      '',
    ].join('\n'),
    'utf8',
  )
}

beforeEach(() => {
  cwd = mkdtempSync(path.join(tmpdir(), 'wp-readme-drift-'))
  mkdirSync(path.join(cwd, 'blueprints'), { recursive: true })
  writeBlueprint(path.join('planned', 'one.md'))
  writeBlueprint(path.join('in-progress', 'two.md'))
  writeBlueprint(path.join('completed', 'three.md'))
})

afterEach(() => {
  rmSync(cwd, { recursive: true, force: true })
})

describe('auditBlueprintReadmeDrift', () => {
  it('reports a stale generated block', () => {
    writeFileSync(
      path.join(cwd, 'blueprints', 'README.md'),
      [
        '# Blueprints',
        '',
        '<!-- BEGIN: blueprint-index (generated by `wp audit blueprint-readme-drift --fix`) -->',
        '| State | Count | Description |',
        '| ----- | ----: | ----------- |',
        '| `planned/` | 999 | wrong |',
        '<!-- END: blueprint-index -->',
        '',
        '## Authoring',
        '',
        'Keep this prose.',
        '',
      ].join('\n'),
      'utf8',
    )

    const result = auditBlueprintReadmeDrift(cwd)
    expect(result.ok).toBe(false)
    expect(result.violations[0]?.message).toContain("run 'wp audit blueprint-readme-drift --fix'")
  })

  it('rewrites the generated block with --fix and preserves prose outside the markers', () => {
    const readmePath = path.join(cwd, 'blueprints', 'README.md')
    writeFileSync(
      readmePath,
      ['# Blueprints', '', '## Authoring', '', 'Keep this prose.', ''].join('\n'),
      'utf8',
    )

    const result = auditBlueprintReadmeDrift(cwd, { fix: true })
    expect(result.ok).toBe(true)

    const updated = readFileSync(readmePath, 'utf8')
    expect(updated).toContain('| `planned/` | 1 |')
    expect(updated).toContain('| `in-progress/` | 1 |')
    expect(updated).toContain('| `completed/` | 1 |')
    expect(updated).toContain('Keep this prose.')
    expect(updated).toContain('## Authoring')
  })

  it('passes when the generated block is already in sync', () => {
    const readmePath = path.join(cwd, 'blueprints', 'README.md')
    writeFileSync(
      readmePath,
      ['# Blueprints', '', '## Authoring', '', 'Keep this prose.', ''].join('\n'),
      'utf8',
    )
    auditBlueprintReadmeDrift(cwd, { fix: true })

    const result = auditBlueprintReadmeDrift(cwd)
    expect(result.ok).toBe(true)
    expect(result.violations).toHaveLength(0)
  })

  it('supports repos whose canonical blueprint root is webpresso/blueprints', () => {
    rmSync(path.join(cwd, 'blueprints'), { recursive: true, force: true })
    mkdirSync(path.join(cwd, 'webpresso', 'blueprints'), { recursive: true })
    writeFileSync(path.join(cwd, 'webpresso', 'config.yaml'), 'project:\n  name: test\n', 'utf8')

    const nestedBlueprint = path.join(cwd, 'webpresso', 'blueprints', 'planned', 'one.md')
    mkdirSync(path.dirname(nestedBlueprint), { recursive: true })
    writeFileSync(
      nestedBlueprint,
      [
        '---',
        'type: blueprint',
        'title: Example',
        'owner: test',
        'status: planned',
        'complexity: S',
        "created: '2026-06-04'",
        "last_updated: '2026-06-04'",
        '---',
        '',
        '# Example',
        '',
        '#### Task 1.1: Example',
        '',
        '**Status:** todo',
        '',
        '**Acceptance:**',
        '',
        '- [ ] Example',
        '',
      ].join('\n'),
      'utf8',
    )

    const readmePath = path.join(cwd, 'webpresso', 'blueprints', 'README.md')
    writeFileSync(readmePath, ['# Blueprints', '', '## Authoring', '', 'Keep this prose.', ''].join('\n'), 'utf8')

    const result = auditBlueprintReadmeDrift(cwd, { fix: true })
    expect(result.ok).toBe(true)
    expect(readFileSync(readmePath, 'utf8')).toContain('| `planned/` | 1 |')
  })
})
