import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { resolveBlueprintRoot } from "#utils/blueprint-root.js";

import type { RepoAuditResult } from "./repo-guardrails.js";

const BEGIN_MARKER =
  "<!-- BEGIN: blueprint-index (generated by `wp audit blueprint-readme-drift --fix`) -->";
const END_MARKER = "<!-- END: blueprint-index -->";
const README_INSERT_HEADING = "## Authoring";
function staleMessage(readmeRelativePath: string): string {
  return `${readmeRelativePath} index block is stale — run 'wp audit blueprint-readme-drift --fix'`;
}

const STATE_ROWS = [
  ["draft", "early-stage sketches. Expect churn; move to `planned/` once scoped."],
  ["planned", "committed-to specs, ready to pick up."],
  ["in-progress", "actively being executed. At most 3 active blueprints per lane."],
  ["completed", "execution finished and verified. Kept for reference."],
  ["parked", "intentionally paused. Include a reason in the spec's frontmatter."],
  ["archived", "superseded or abandoned. Not deleted — the record matters."],
] as const;

export interface BlueprintReadmeDriftOptions {
  fix?: boolean;
}

export function refreshBlueprintReadmeIndex(cwd: string = process.cwd()): void {
  const readmePath = resolveBlueprintReadmePath(cwd);
  if (!existsSync(readmePath)) return;

  const result = auditBlueprintReadmeDrift(cwd, { fix: true });
  if (!result.ok) {
    throw new Error(
      result.violations.map((violation) => `${violation.file}: ${violation.message}`).join("\n"),
    );
  }
}

function resolveBlueprintReadmePath(cwd: string): string {
  return path.join(resolveBlueprintRoot(cwd), "README.md");
}

function blueprintReadmeRelativePath(cwd: string): string {
  return path.relative(cwd, resolveBlueprintReadmePath(cwd)).replace(/\\/g, "/");
}

function renderGeneratedBlock(): string {
  const stateColumnWidth = Math.max(
    "State".length,
    ...STATE_ROWS.map(([state]) => state.length + 3),
  );
  const descriptionColumnWidth = Math.max(
    "Description".length,
    ...STATE_ROWS.map(([, description]) => description.length),
  );
  const row = (state: string, description: string): string =>
    `| ${state.padEnd(stateColumnWidth, " ")} | ${description.padEnd(descriptionColumnWidth, " ")} |`;
  const lines = [
    BEGIN_MARKER,
    "",
    row("State", "Description"),
    `| ${"-".repeat(stateColumnWidth)} | ${"-".repeat(descriptionColumnWidth)} |`,
    ...STATE_ROWS.map(([state, description]) => row(`\`${state}/\``, description)),
    "",
    END_MARKER,
  ];
  return `${lines.join("\n")}\n`;
}

function replaceExistingBlock(markdown: string, block: string): string {
  const start = markdown.indexOf(BEGIN_MARKER);
  const end = markdown.indexOf(END_MARKER);
  if (start >= 0 && end >= start) {
    const afterEnd = end + END_MARKER.length;
    return `${markdown.slice(0, start)}${block}${markdown.slice(afterEnd)}`;
  }

  const insertAt = markdown.indexOf(README_INSERT_HEADING);
  if (insertAt >= 0) {
    return `${markdown.slice(0, insertAt).replace(/\n*$/, "\n\n")}${block}${markdown.slice(insertAt)}`;
  }

  return `${markdown.replace(/\s*$/, "\n\n")}${block}`;
}

function extractExistingBlock(markdown: string): string | null {
  const start = markdown.indexOf(BEGIN_MARKER);
  const end = markdown.indexOf(END_MARKER);
  if (start < 0 || end < start) return null;
  return markdown.slice(start, end + END_MARKER.length);
}

export function auditBlueprintReadmeDrift(
  cwd: string = process.cwd(),
  options: BlueprintReadmeDriftOptions = {},
): RepoAuditResult {
  const readmePath = resolveBlueprintReadmePath(cwd);
  const readmeRelativePath = blueprintReadmeRelativePath(cwd);
  if (!existsSync(readmePath)) {
    return {
      ok: false,
      title: "Blueprint README drift",
      checked: 1,
      violations: [{ file: readmeRelativePath, message: `${readmeRelativePath} is missing` }],
    };
  }

  const current = readFileSync(readmePath, "utf8");
  const expectedBlock = renderGeneratedBlock();
  const currentBlock = extractExistingBlock(current);
  const updated = replaceExistingBlock(current, expectedBlock);
  const isInSync = currentBlock !== null && currentBlock.trimEnd() === expectedBlock.trimEnd();

  if (!isInSync && options.fix) {
    mkdirSync(path.dirname(readmePath), { recursive: true });
    writeFileSync(readmePath, updated, "utf8");
    return {
      ok: true,
      title: "Blueprint README drift",
      checked: 1,
      violations: [],
    };
  }

  return {
    ok: isInSync,
    title: "Blueprint README drift",
    checked: 1,
    violations: isInSync
      ? []
      : [{ file: readmeRelativePath, message: staleMessage(readmeRelativePath) }],
  };
}
