import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { scanBlueprintDirectory } from '#service/scanner.js'
import { resolveBlueprintRoot } from '#utils/blueprint-root.js'
import { parseBlueprintDocumentRelativePath } from '#utils/document-paths.js'

import type { RepoAuditResult } from './repo-guardrails.js'

const BEGIN_MARKER =
  '<!-- BEGIN: blueprint-index (generated by `wp audit blueprint-readme-drift --fix`) -->'
const END_MARKER = '<!-- END: blueprint-index -->'
const README_INSERT_HEADING = '## Authoring'
function staleMessage(readmeRelativePath: string): string {
  return `${readmeRelativePath} index block is stale — run 'wp audit blueprint-readme-drift --fix'`
}

const STATE_ROWS = [
  ['draft', 'early-stage sketches. Expect churn; move to `planned/` once scoped.'],
  ['planned', 'committed-to specs, ready to pick up.'],
  ['in-progress', 'actively being executed. At most 3 active blueprints per lane.'],
  ['completed', 'execution finished and verified. Kept for reference.'],
  ['parked', "intentionally paused. Include a reason in the spec's frontmatter."],
  ['archived', 'superseded or abandoned. Not deleted — the record matters.'],
] as const

type BlueprintState = (typeof STATE_ROWS)[number][0]

export interface BlueprintReadmeDriftOptions {
  fix?: boolean
}

export function refreshBlueprintReadmeIndex(cwd: string = process.cwd()): void {
  const readmePath = resolveBlueprintReadmePath(cwd)
  if (!existsSync(readmePath)) return

  const result = auditBlueprintReadmeDrift(cwd, { fix: true })
  if (!result.ok) {
    throw new Error(
      result.violations.map((violation) => `${violation.file}: ${violation.message}`).join('\n'),
    )
  }
}

function resolveBlueprintReadmePath(cwd: string): string {
  return path.join(resolveBlueprintRoot(cwd), 'README.md')
}

function blueprintReadmeRelativePath(cwd: string): string {
  return path.relative(cwd, resolveBlueprintReadmePath(cwd)).replace(/\\/g, '/')
}

function initialCounts(): Record<BlueprintState, number> {
  return {
    draft: 0,
    planned: 0,
    'in-progress': 0,
    completed: 0,
    parked: 0,
    archived: 0,
  }
}

function listVisibleBlueprintPaths(cwd: string, trackedRoot: string): readonly string[] | null {
  const result = spawnSync(
    'git',
    ['ls-files', '--cached', '--others', '--exclude-standard', '--full-name', trackedRoot],
    {
      cwd,
      encoding: 'utf8',
      timeout: 5000,
    },
  )
  if (result.status !== 0 || result.error != null) return null

  const deleted = spawnSync('git', ['ls-files', '--deleted', '--full-name', trackedRoot], {
    cwd,
    encoding: 'utf8',
    timeout: 5000,
  })
  if (deleted.status !== 0 || deleted.error != null) return null

  const deletedPaths = new Set(deleted.stdout.split('\n').filter(Boolean))
  return result.stdout
    .split('\n')
    .filter((filePath) => filePath.length > 0 && !deletedPaths.has(filePath))
}

function countBlueprintsByState(cwd: string): Record<BlueprintState, number> {
  const counts = initialCounts()
  const blueprintsRoot = resolveBlueprintRoot(cwd)
  if (!existsSync(blueprintsRoot)) return counts

  // Prefer git ls-files so counts reflect the visible, non-ignored working
  // tree: tracked files plus untracked additions, minus deleted tracked files.
  // This keeps --fix trustworthy while lifecycle moves are still unstaged.
  const trackedRoot = path.relative(cwd, blueprintsRoot).replace(/\\/g, '/')
  const visible = listVisibleBlueprintPaths(cwd, trackedRoot)
  if (visible !== null) {
    for (const filePath of visible) {
      const prefix = `${trackedRoot}/`
      const afterBlueprints = filePath.startsWith(prefix) ? filePath.slice(prefix.length) : filePath
      const parsed = parseBlueprintDocumentRelativePath(afterBlueprints)
      if (!parsed) continue
      counts[parsed.state as BlueprintState] += 1
    }
    return counts
  }

  // Fallback for non-git contexts (e.g. bare extract, temp directory).
  const scanned = scanBlueprintDirectory({
    baseDir: blueprintsRoot,
    includeSpecialFolders: true,
  })

  for (const blueprint of scanned) {
    const relativePath = path.relative(blueprintsRoot, blueprint.path).replace(/\\/g, '/')
    const parsed = parseBlueprintDocumentRelativePath(relativePath)
    if (!parsed) continue
    counts[parsed.state as BlueprintState] += 1
  }

  return counts
}

function renderGeneratedBlock(counts: Record<BlueprintState, number>): string {
  const lines = [
    BEGIN_MARKER,
    '| State | Count | Description |',
    '| ----- | ----: | ----------- |',
    ...STATE_ROWS.map(
      ([state, description]) => `| \`${state}/\` | ${counts[state]} | ${description} |`,
    ),
    END_MARKER,
  ]
  return `${lines.join('\n')}\n`
}

function replaceExistingBlock(markdown: string, block: string): string {
  const start = markdown.indexOf(BEGIN_MARKER)
  const end = markdown.indexOf(END_MARKER)
  if (start >= 0 && end >= start) {
    const afterEnd = end + END_MARKER.length
    return `${markdown.slice(0, start)}${block}${markdown.slice(afterEnd)}`
  }

  const insertAt = markdown.indexOf(README_INSERT_HEADING)
  if (insertAt >= 0) {
    return `${markdown.slice(0, insertAt).replace(/\n*$/, '\n\n')}${block}${markdown.slice(insertAt)}`
  }

  return `${markdown.replace(/\s*$/, '\n\n')}${block}`
}

function extractExistingBlock(markdown: string): string | null {
  const start = markdown.indexOf(BEGIN_MARKER)
  const end = markdown.indexOf(END_MARKER)
  if (start < 0 || end < start) return null
  return markdown.slice(start, end + END_MARKER.length)
}

export function auditBlueprintReadmeDrift(
  cwd: string = process.cwd(),
  options: BlueprintReadmeDriftOptions = {},
): RepoAuditResult {
  const readmePath = resolveBlueprintReadmePath(cwd)
  const readmeRelativePath = blueprintReadmeRelativePath(cwd)
  if (!existsSync(readmePath)) {
    return {
      ok: false,
      title: 'Blueprint README drift',
      checked: 1,
      violations: [{ file: readmeRelativePath, message: `${readmeRelativePath} is missing` }],
    }
  }

  const current = readFileSync(readmePath, 'utf8')
  const expectedBlock = renderGeneratedBlock(countBlueprintsByState(cwd))
  const currentBlock = extractExistingBlock(current)
  const updated = replaceExistingBlock(current, expectedBlock)
  const isInSync = currentBlock !== null && currentBlock.trimEnd() === expectedBlock.trimEnd()

  if (!isInSync && options.fix) {
    mkdirSync(path.dirname(readmePath), { recursive: true })
    writeFileSync(readmePath, updated, 'utf8')
    return {
      ok: true,
      title: 'Blueprint README drift',
      checked: 1,
      violations: [],
    }
  }

  return {
    ok: isInSync,
    title: 'Blueprint README drift',
    checked: 1,
    violations: isInSync
      ? []
      : [{ file: readmeRelativePath, message: staleMessage(readmeRelativePath) }],
  }
}
