import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { tmpdir } from "node:os";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { auditBlueprintReadmeDrift } from "./blueprint-readme-drift.js";

let cwd: string;

function writeBlueprint(relativePath: string): void {
  const fullPath = path.join(cwd, "blueprints", relativePath);
  mkdirSync(path.dirname(fullPath), { recursive: true });
  writeFileSync(
    fullPath,
    [
      "---",
      "type: blueprint",
      "title: Example",
      "owner: test",
      `status: ${relativePath.split(path.sep)[0]}`,
      "complexity: S",
      "created: '2026-06-04'",
      "last_updated: '2026-06-04'",
      "---",
      "",
      "# Example",
      "",
      "#### Task 1.1: Example",
      "",
      "**Status:** todo",
      "",
      "**Acceptance:**",
      "",
      "- [ ] Example",
      "",
    ].join("\n"),
    "utf8",
  );
}

function runGit(args: readonly string[]): void {
  execFileSync("git", args, { cwd, stdio: "ignore" });
}

function initGitRepo(): void {
  runGit(["init"]);
  runGit(["config", "user.email", "test@example.com"]);
  runGit(["config", "user.name", "Test User"]);
  runGit(["config", "core.hooksPath", "/dev/null"]);
}

beforeEach(() => {
  cwd = mkdtempSync(path.join(tmpdir(), "wp-readme-drift-"));
  mkdirSync(path.join(cwd, "blueprints"), { recursive: true });
  writeBlueprint(path.join("planned", "one.md"));
  writeBlueprint(path.join("in-progress", "two.md"));
  writeBlueprint(path.join("completed", "three.md"));
});

afterEach(() => {
  rmSync(cwd, { recursive: true, force: true });
});

describe("auditBlueprintReadmeDrift", () => {
  it("reports the retired generated block", () => {
    writeFileSync(
      path.join(cwd, "blueprints", "README.md"),
      [
        "# Blueprints",
        "",
        "<!-- BEGIN: blueprint-index (generated by `wp audit blueprint-readme-drift --fix`) -->",
        "| State | Count | Description |",
        "| ----- | ----: | ----------- |",
        "| `planned/` | 999 | wrong |",
        "<!-- END: blueprint-index -->",
        "",
        "## Authoring",
        "",
        "Keep this prose.",
        "",
      ].join("\n"),
      "utf8",
    );

    const result = auditBlueprintReadmeDrift(cwd);
    expect(result.ok).toBe(false);
    expect(result.violations[0]?.message).toContain("retired generated blueprint index block");
  });

  it("removes the retired generated block with --fix and preserves prose outside the markers", () => {
    const readmePath = path.join(cwd, "blueprints", "README.md");
    writeFileSync(
      readmePath,
      [
        "# Blueprints",
        "",
        "<!-- BEGIN: blueprint-index (generated by `wp audit blueprint-readme-drift --fix`) -->",
        "| State | Count | Description |",
        "| ----- | ----: | ----------- |",
        "| `planned/` | 999 | wrong |",
        "<!-- END: blueprint-index -->",
        "",
        "## Authoring",
        "",
        "Keep this prose.",
        "",
      ].join("\n"),
      "utf8",
    );

    const result = auditBlueprintReadmeDrift(cwd, { fix: true });
    expect(result.ok).toBe(true);

    const updated = readFileSync(readmePath, "utf8");
    expect(updated).not.toContain("BEGIN: blueprint-index");
    expect(updated).not.toContain("END: blueprint-index");
    expect(updated).not.toContain("| State | Count | Description |");
    expect(updated).toContain("Keep this prose.");
    expect(updated).toContain("## Authoring");
  });

  it("keeps the README stable across uncommitted lifecycle moves", () => {
    const readmePath = path.join(cwd, "blueprints", "README.md");
    writeFileSync(
      readmePath,
      ["# Blueprints", "", "## Authoring", "", "Keep this prose.", ""].join("\n"),
      "utf8",
    );
    auditBlueprintReadmeDrift(cwd, { fix: true });
    const before = readFileSync(readmePath, "utf8");

    initGitRepo();
    runGit(["add", "blueprints"]);
    runGit(["commit", "-m", "seed blueprints"]);

    const fromPath = path.join(cwd, "blueprints", "planned", "one.md");
    const toPath = path.join(cwd, "blueprints", "completed", "one.md");
    renameSync(fromPath, toPath);
    writeFileSync(
      toPath,
      readFileSync(toPath, "utf8").replace("status: planned", "status: completed"),
    );

    const result = auditBlueprintReadmeDrift(cwd, { fix: true });
    expect(result.ok).toBe(true);
    expect(readFileSync(readmePath, "utf8")).toBe(before);
  });

  it("passes when the README has no managed generated block", () => {
    const readmePath = path.join(cwd, "blueprints", "README.md");
    writeFileSync(
      readmePath,
      ["# Blueprints", "", "## Authoring", "", "Keep this prose.", ""].join("\n"),
      "utf8",
    );

    const result = auditBlueprintReadmeDrift(cwd);
    expect(result.ok).toBe(true);
    expect(result.violations).toHaveLength(0);
  });

  it("fails loudly on malformed retired block markers", () => {
    const readmePath = path.join(cwd, "blueprints", "README.md");
    writeFileSync(
      readmePath,
      [
        "# Blueprints",
        "",
        "<!-- BEGIN: blueprint-index (generated by `wp audit blueprint-readme-drift --fix`) -->",
        "| State | Description |",
        "",
        "## Authoring",
        "",
      ].join("\n"),
      "utf8",
    );

    const result = auditBlueprintReadmeDrift(cwd, { fix: true });
    expect(result.ok).toBe(false);
    expect(result.violations[0]?.message).toContain("malformed retired blueprint index markers");
  });

  it("supports repos whose canonical blueprint root is webpresso/blueprints", () => {
    rmSync(path.join(cwd, "blueprints"), { recursive: true, force: true });
    mkdirSync(path.join(cwd, "webpresso", "blueprints"), { recursive: true });
    writeFileSync(path.join(cwd, "webpresso", "config.yaml"), "project:\n  name: test\n", "utf8");

    const nestedBlueprint = path.join(cwd, "webpresso", "blueprints", "planned", "one.md");
    mkdirSync(path.dirname(nestedBlueprint), { recursive: true });
    writeFileSync(
      nestedBlueprint,
      [
        "---",
        "type: blueprint",
        "title: Example",
        "owner: test",
        "status: planned",
        "complexity: S",
        "created: '2026-06-04'",
        "last_updated: '2026-06-04'",
        "---",
        "",
        "# Example",
        "",
        "#### Task 1.1: Example",
        "",
        "**Status:** todo",
        "",
        "**Acceptance:**",
        "",
        "- [ ] Example",
        "",
      ].join("\n"),
      "utf8",
    );

    const readmePath = path.join(cwd, "webpresso", "blueprints", "README.md");
    writeFileSync(
      readmePath,
      ["# Blueprints", "", "## Authoring", "", "Keep this prose.", ""].join("\n"),
      "utf8",
    );

    const result = auditBlueprintReadmeDrift(cwd, { fix: true });
    expect(result.ok).toBe(true);
    expect(readFileSync(readmePath, "utf8")).toBe(
      ["# Blueprints", "", "## Authoring", "", "Keep this prose.", ""].join("\n"),
    );
  });

  it("keeps the README stable when blueprint counts change", () => {
    const readmePath = path.join(cwd, "blueprints", "README.md");
    writeFileSync(
      readmePath,
      ["# Blueprints", "", "## Authoring", "", "Keep this prose.", ""].join("\n"),
      "utf8",
    );
    auditBlueprintReadmeDrift(cwd, { fix: true });
    const before = readFileSync(readmePath, "utf8");

    writeBlueprint(path.join("completed", "four.md"));

    const result = auditBlueprintReadmeDrift(cwd);
    expect(result.ok).toBe(true);
    expect(readFileSync(readmePath, "utf8")).toBe(before);
  });
});
