<!--
  AGENTS.md template.

  `ak setup` renders this file with:
  - {{REPOSITORY_MAP}}: bulleted list of workspace packages inferred from
    pnpm-workspace.yaml / package.json workspaces.
  - {{TECH_STACK}}: short description generated from package.json + detected
    frameworks (React, Hono, Drizzle, etc.).
  - {{ESCALATION_MAP}}: user-edited section. Left as a TODO placeholder if
    not specified.
  - {{DURABLE_PLANNING_ROOT}}: defaults to `.agent/planning/`. Override via
    .agent-kitrc.json.
  - {{BLUEPRINTS_DIR}}: defaults to `blueprints`. Override via
    .agent-kitrc.json#blueprintsDir.

  Managed sections in this file are refreshed by agent-kit on `ak sync`.
  Repo-specific edits belong only inside `user-owned` blocks; agent-kit
  preserves those blocks verbatim when it rewrites managed content.
-->

<!-- >>> managed by @webpresso/agent-kit (operating-contract) -->
# Operating Contract

This is the shared working agreement for contributors and coding agents in this
repo. Prefer repo-local instructions when they are more specific than this
starter template, and keep changes small, reviewable, and verified.

## Setup after clone

No agent surfaces are tracked in git — everything is regenerated. After cloning:

```bash
vp install && vp run setup:agent  # setup:agent runs ak setup, which scaffolds .agent/, AGENTS.md, hooks, and runs ak sync
```

Agent-kit is the single source of truth. To customize skills, commands, or
workflows, edit them in `@webpresso/agent-kit`'s catalog and publish — not in
individual repos. The default `omx` preset chains `omx setup --yes --scope user`
and installs missing OMX through `vp install -g oh-my-codex`. The default `omc`
preset ensures OMC through Claude Code's plugin marketplace in user scope when
`claude` is on `PATH`. `wp setup --project` requests project-scoped OMX/OMC
setup. `wp setup`
also repairs the managed `.gitignore` block for regenerated agent surfaces so
repo-local `.codex/`, `.omx/`, `.agent/`, and IDE projection outputs stay out
of Git.

## Plan

Use blueprints for non-trivial work. Blueprint specs live in
[`{{BLUEPRINTS_DIR}}/`](./{{BLUEPRINTS_DIR}}/) with lifecycle directories such
as `planned/`, `in-progress/`, and `completed/`. Keep each blueprint's tasks,
dependencies, verification commands, and acceptance criteria current before
execution.

Slash-commands and skills are loaded from agent-kit's catalog at setup time:

- `.agent/commands/` — slash-command sources (from catalog).
- `.agent/skills/` — skills (from catalog); edit in agent-kit, not here.

## Implement

Use this repo's task runner or package scripts instead of guessing commands from
memory. If a wrapped command exists, prefer it over direct tool invocation so the
repo can apply its environment, caching, and policy consistently.

Before large edits, inspect nearby patterns and reuse existing utilities. Avoid
new dependencies unless the task explicitly requires them.

## Verify

Before claiming completion, run the narrowest checks that prove the changed
behavior and any broader checks this repo requires. Typical gates are:

- typecheck
- lint / format check
- affected tests
- docs or blueprint validation when docs/plans changed
- `ak sync --check` after `ak setup` to verify surfaces are in sync

If a gate fails, fix the root cause or record the blocker with evidence.

## Communicate

Commit messages, PR descriptions, and decision records should explain why the
change exists, what tradeoffs were made, and what was verified. Record durable
architecture decisions in this repo's ADR or planning location if one exists.
<!-- <<< managed by @webpresso/agent-kit (operating-contract) -->

<!-- >>> user-owned (repo-customizations) -->
## Repo-specific customizations

Add repo-local instructions, preferences, and exceptions here. Content inside
this block is preserved verbatim across `ak sync` runs.
<!-- <<< user-owned (repo-customizations) -->

<!-- >>> managed by @webpresso/agent-kit (planning-and-release) -->
## Safety boundaries

- Do not commit secrets or credentials.
- Do not commit agent surfaces (`.agent/`, `.agents/`, `.gemini/`, `.cursor/`,
  `.windsurf/`, `.omx/`, `.codex/`, `.opencode/`) — they are gitignored and
  regenerated by `ak setup` / `omx setup`.
- Do not hand-edit generated or derived surfaces; edit the catalog in agent-kit.
- Do not bypass hooks or verification gates to force a change through.
- Do not assume Webpresso-specific paths, tools, or runtimes exist unless this
  repo documents them.
- Surface conflicts between this file and deeper repo instructions instead of
  silently ignoring either.

## Durable planning surface

- Materialized by setup: blueprint lifecycle directories under
  `{{BLUEPRINTS_DIR}}/` (`planned/`, `in-progress/`, `completed/`) and durable
  plan files under `{{DURABLE_PLANNING_ROOT}}plans/` when PRDs or test specs
  are generated.
- Generated on demand (not created by setup): boundary contracts at
  `{{DURABLE_PLANNING_ROOT}}contracts/`, lifecycle state at
  `{{DURABLE_PLANNING_ROOT}}state/`, session notes at
  `{{DURABLE_PLANNING_ROOT}}notepad.md`, and project memory at
  `{{DURABLE_PLANNING_ROOT}}project-memory.json`.

If work changes workspace ownership, build boundaries, or cross-package
consumption mode, update the relevant boundary contract before claiming the plan
is ready.

## Releases

All packages in the webpresso public umbrella use **Changesets**. Never push
`v*` tags or manually bump `package.json#version`.

To ship a change:
1. `vp run changeset` — describe the change and select the bump type.
2. Commit the generated `.changeset/<name>.md` alongside your code.
3. Merge to `main`. CI opens a **"Version Packages"** PR automatically.
4. Merge that PR — CI publishes to GitHub Packages.

```bash
vp run changeset:status   # see pending changesets
```

Full protocol: `.agent/rules/changeset-release.md`

## Package conventions

- No `../` parent-relative imports — use workspace deps + subpath exports.
- No `.mjs` source files — write `.ts` (with Bun/Node shebang if needed).
- Use `vp` as the command facade (`vp install`, `vp run <script>`) so Vite+ selects the repo-declared package-manager substrate. Do not call `npm`, `npx`, or raw package-manager globals for repo workflows unless a deeper repo instruction explicitly requires it.
- All packages: `"type": "module"`, `publishConfig` → GitHub Packages registry.
- Auth: `GH_PACKAGES_TOKEN` env var consumed by `.npmrc`. Never hardcode tokens.

Full details: `.agent/rules/package-conventions.md`

## Repository map

{{REPOSITORY_MAP}}

## Tech stack

{{TECH_STACK}}
<!-- <<< managed by @webpresso/agent-kit (planning-and-release) -->

<!-- >>> user-owned (escalation-map) -->
## Escalation map

{{ESCALATION_MAP}}
<!-- <<< user-owned (escalation-map) -->
