<!--
  AGENTS.md template.

  `ak setup` renders this file with:
  - {{REPOSITORY_MAP}}: bulleted list of workspace packages inferred from
    pnpm-workspace.yaml / package.json workspaces.
  - {{TECH_STACK}}: short description generated from package.json + detected
    frameworks (React, Hono, Drizzle, etc.).
  - {{ESCALATION_MAP}}: user-edited section. Left as a TODO placeholder if
    not specified.
  - {{DURABLE_PLANNING_ROOT}}: defaults to `.agent/planning/`. Override via
    .agent-kitrc.json.

  After rendering, this file belongs to the consumer repo. Agent Kit does not
  rewrite it on re-runs unless `ak setup --overwrite` is used.
-->

# Operating Contract

This is the shared working agreement for contributors and coding agents in this
repo. Prefer repo-local instructions when they are more specific than this
starter template, and keep changes small, reviewable, and verified.

## Setup after clone

No agent surfaces are tracked in git — everything is regenerated. After cloning:

```bash
pnpm install && pnpm setup:agent  # pnpm setup:agent runs ak setup, which scaffolds .agent/, AGENTS.md, hooks, and runs symlink sync
```

Agent-kit is the single source of truth. To customize skills, commands, or
workflows, edit them in `@webpresso/agent-kit`'s catalog and publish — not in
individual repos. The `--with omx` preset chains `omx setup --yes`.

## Plan

Use blueprints for non-trivial work. Blueprint specs live in
[`blueprints/`](./blueprints/) with lifecycle directories such as `planned/`,
`in-progress/`, and `completed/`. Keep each blueprint's tasks, dependencies,
verification commands, and acceptance criteria current before execution.

Slash-commands and skills are loaded from agent-kit's catalog at setup time:

- `.agent/commands/` — slash-command sources (from catalog).
- `.agent/skills/` — skills (from catalog); edit in agent-kit, not here.

## Implement

Use this repo's task runner or package scripts instead of guessing commands from
memory. If a wrapped command exists, prefer it over direct tool invocation so the
repo can apply its environment, caching, and policy consistently.

Before large edits, inspect nearby patterns and reuse existing utilities. Avoid
new dependencies unless the task explicitly requires them.

## Verify

Before claiming completion, run the narrowest checks that prove the changed
behavior and any broader checks this repo requires. Typical gates are:

- typecheck
- lint / format check
- affected tests
- docs or blueprint validation when docs/plans changed
- `ak symlink check` after `ak setup` to verify surfaces are in sync

If a gate fails, fix the root cause or record the blocker with evidence.

## Communicate

Commit messages, PR descriptions, and decision records should explain why the
change exists, what tradeoffs were made, and what was verified. Record durable
architecture decisions in this repo's ADR or planning location if one exists.

## Safety boundaries

- Do not commit secrets or credentials.
- Do not commit agent surfaces (`.agent/`, `.agents/`, `.gemini/`, `.cursor/`,
  `.windsurf/`, `.omx/`, `.codex/`, `.opencode/`) — they are gitignored and
  regenerated by `ak setup` / `omx setup`.
- Do not hand-edit generated or derived surfaces; edit the catalog in agent-kit.
- Do not bypass hooks or verification gates to force a change through.
- Do not assume Webpresso-specific paths, tools, or runtimes exist unless this
  repo documents them.
- Surface conflicts between this file and deeper repo instructions instead of
  silently ignoring either.

## Durable planning surface

- PRDs: `{{DURABLE_PLANNING_ROOT}}/plans/prd-<slug>.md`
- Test specs: `{{DURABLE_PLANNING_ROOT}}/plans/test-spec-<slug>.md`
- Boundary contracts: `{{DURABLE_PLANNING_ROOT}}/contracts/*.md`
- Lifecycle state: `{{DURABLE_PLANNING_ROOT}}/state/lifecycle/<slug>.json`
- Session notes: `{{DURABLE_PLANNING_ROOT}}/notepad.md`
- Project memory: `{{DURABLE_PLANNING_ROOT}}/project-memory.json`

If work changes workspace ownership, build boundaries, or cross-package
consumption mode, update the relevant boundary contract before claiming the plan
is ready.

## Releases

All packages in the webpresso public umbrella use **Changesets**. Never push
`v*` tags or manually bump `package.json#version`.

To ship a change:
1. `pnpm changeset` — describe the change and select the bump type.
2. Commit the generated `.changeset/<name>.md` alongside your code.
3. Merge to `main`. CI opens a **"Version Packages"** PR automatically.
4. Merge that PR — CI publishes to GitHub Packages.

```bash
pnpm changeset:status   # see pending changesets
```

Full protocol: `.agent/rules/changeset-release.md`

## Package conventions

- No `../` parent-relative imports — use workspace deps + subpath exports.
- No `.mjs` source files — write `.ts` (with Bun/Node shebang if needed).
- `pnpm` only (`pnpm@10.x`). Run scripts via `pnpm run <script>`.
- All packages: `"type": "module"`, `publishConfig` → GitHub Packages registry.
- Auth: `GH_PACKAGES_TOKEN` env var consumed by `.npmrc`. Never hardcode tokens.

Full details: `.agent/rules/package-conventions.md`

## Repository map

{{REPOSITORY_MAP}}

## Tech stack

{{TECH_STACK}}

## Escalation map

{{ESCALATION_MAP}}
