/**
 * Baseline blueprint MCP create-contract tests.
 *
 * Validation, registration, task-next, aggregate-project reads, verify, and
 * platform-first scenarios live in sibling files so Vitest can use file-level
 * workers without rebuilding unrelated cold-start fixtures.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { z } from "zod";

import {
  callTool,
  cleanupTempDir,
  makeEmptyProjectionBlueprintHarness,
  parseResult,
  type ToolMap,
} from "./blueprint-server.test-harness.js";

let tmpDir: string;
let tools: ToolMap;

function writeBlueprintReadme(root: string): void {
  writeFileSync(
    path.join(root, "blueprints", "README.md"),
    [
      "# Blueprints",
      "",
      "<!-- BEGIN: blueprint-index (generated by `wp audit blueprint-readme-drift --fix`) -->",
      "| State | Description |",
      "| ----- | ----------- |",
      "| `draft/` | early-stage sketches. Expect churn; move to `planned/` once scoped. |",
      "| `planned/` | committed-to specs, ready to pick up. |",
      "| `in-progress/` | actively being executed. At most 3 active blueprints per lane. |",
      "| `completed/` | execution finished and verified. Kept for reference. |",
      "| `parked/` | intentionally paused. Include a reason in the spec's frontmatter. |",
      "| `archived/` | superseded or abandoned. Not deleted — the record matters. |",
      "<!-- END: blueprint-index -->",
      "",
      "## Authoring",
      "",
      "Keep this prose.",
      "",
    ].join("\n"),
    "utf8",
  );
}

beforeEach(async () => {
  ({ tmpDir, tools } = await makeEmptyProjectionBlueprintHarness("wp-bs-create-"));
});

afterEach(() => {
  cleanupTempDir(tmpDir);
});

describe("wp_blueprint_create", () => {
  it("creates blueprint markdown and returns slug + path", async () => {
    writeBlueprintReadme(tmpDir);
    const result = await callTool(tools, "wp_blueprint_create", {
      project_id: tmpDir,
      title: "My Created Blueprint",
      goal: "Test the create handler end-to-end",
      complexity: "S",
    });
    const data = parseResult(result) as {
      slug: string;
      path: string;
      next_action: { kind: string };
      failures: string[];
    };
    expect(result.isError).toStrictEqual(false);
    expect(data.slug).toBe("my-created-blueprint");
    expect(data.path).toContain(".md");
    expect(existsSync(data.path)).toBe(true);
    expect(data.next_action.kind).toBe("verify_task");
    expect(data.failures).toStrictEqual([]);
    const readmeText = readFileSync(path.join(tmpDir, "blueprints", "README.md"), "utf8");
    expect(readmeText).toContain("Keep this prose.");
    expect(readmeText).not.toContain("BEGIN: blueprint-index");
  });

  it("re-ingests so the new blueprint appears in wp_blueprint_list", async () => {
    await callTool(tools, "wp_blueprint_create", {
      project_id: tmpDir,
      title: "Ingest Check Blueprint",
      goal: "Verify re-ingest after create",
    });
    const listResult = await callTool(tools, "wp_blueprint_list", { status: "draft" });
    const listData = parseResult(listResult) as {
      blueprints: Array<{ slug: string }>;
    };
    const slugs = listData.blueprints.map((b) => b.slug);
    expect(slugs).toContain("ingest-check-blueprint");
  });

  it("ignores aggregate scope field on mutation input", async () => {
    const result = await callTool(tools, "wp_blueprint_create", {
      project_id: tmpDir,
      title: "Scope Test Blueprint",
      goal: "Test scope field handling",
      scope: "all",
    });
    const data = parseResult(result) as Record<string, unknown>;
    expect(result.isError).toStrictEqual(false);
    expect("scope" in data).toBe(false);
  });

  it("returns validation error when required fields are missing", async () => {
    const result = await callTool(tools, "wp_blueprint_create", { project_id: tmpDir });
    expect(result.isError).toStrictEqual(true);
  });

  it("MutationTarget schema parse rejects unknown scope field at type level", () => {
    const MutationTargetSchema = z.object({ project_id: z.string() });
    const parsed = MutationTargetSchema.safeParse({ project_id: "test", scope: "all" });
    expect(parsed.success).toBe(true);
    if (parsed.success) {
      expect("scope" in parsed.data).toBe(false);
    }
  });
});

describe("wp_blueprint_put", () => {
  const document = {
    type: "blueprint",
    title: "Structured Put Blueprint",
    status: "draft",
    complexity: "S",
    owner: "tester",
    created: "2026-05-29",
    last_updated: "2026-05-29",
    product_wedge_anchor: {
      stage_outcome: "Phase 1 — prove structured blueprint upserts",
      consuming_surface: "wp blueprint MCP tools",
      new_user_visible_capability: "Users can upsert a blueprint via structured input",
    },
    summary: "Blueprint used to test the whole-document put path.",
    tasks: [
      {
        id: "1.1",
        title: "Write the first structured task",
        status: "todo",
        wave: "0",
        acceptance: ["The first structured task exists in markdown"],
      },
    ],
  } as const;

  const trustDossier = {
    readiness: {
      promotion_ready: true,
      unresolved_count: 0,
      verified_at: "2026-06-22T00:00:00.000Z",
      verified_head: "0123456789abcdef0123456789abcdef01234567",
      trust_gate_version: "v1",
    },
    material_claims: [
      {
        id: "C1",
        claim: "The structured put path has repository-backed evidence.",
        evidence: "repo:package.json",
      },
    ],
    material_decisions: [
      {
        id: "D1",
        decision: "Dossier authoring",
        chosen_option: "Use structured trust_dossier input.",
        rejected_alternatives: "Embed markdown in summary.",
        rationale: "The sanctioned writer should render gate-consumable markdown.",
      },
    ],
    promotion_gates: [
      {
        gate: "lint",
        command: "wp lint",
        expected_outcome: "pass",
        last_result: "pending",
      },
    ],
    residual_unknowns: [],
  } as const;

  it("renders structured trust_dossier after tasks using gate-required subsection text", async () => {
    const result = await callTool(tools, "wp_blueprint_put", {
      project_id: tmpDir,
      slug: "structured-put-blueprint",
      document: { ...document, trust_dossier: trustDossier },
    });
    const data = parseResult(result) as { path: string };

    expect(result.isError).toStrictEqual(false);
    const written = readFileSync(data.path, "utf8");
    expect(written.indexOf("#### Task 1.1")).toBeLessThan(written.indexOf("## Trust Dossier"));
    expect(written).toContain("### Readiness Verdict");
    expect(written).toContain("### Material Claims");
    expect(written).toContain("### Material Decisions");
    expect(written).toContain("### Promotion Gates");
    expect(written).toContain("### Residual Unknowns\n\nNone.");
    expect(written).toContain(
      "| C1 | The structured put path has repository-backed evidence. | repo:package.json |",
    );
  });

  it("rejects invalid trust_dossier evidence and gate commands before writing", async () => {
    const lineNumberEvidence = await callTool(tools, "wp_blueprint_put", {
      project_id: tmpDir,
      slug: "line-number-evidence-blueprint",
      document: {
        ...document,
        trust_dossier: {
          ...trustDossier,
          material_claims: [
            {
              ...trustDossier.material_claims[0],
              evidence: "repo:package.json:1",
            },
          ],
        },
      },
    });
    expect(lineNumberEvidence.isError).toStrictEqual(true);
    expect(lineNumberEvidence.content[0]?.text).toMatch(/repo evidence path does not exist/i);

    const nonWpGate = await callTool(tools, "wp_blueprint_put", {
      project_id: tmpDir,
      slug: "non-wp-gate-blueprint",
      document: {
        ...document,
        trust_dossier: {
          ...trustDossier,
          promotion_gates: [
            {
              ...trustDossier.promotion_gates[0],
              command: "node scripts/check.js",
            },
          ],
        },
      },
    });
    expect(nonWpGate.isError).toStrictEqual(true);
    expect(nonWpGate.content[0]?.text).toMatch(/must use wp facade commands/i);
  });

  it("promotes a blueprint authored through structured trust_dossier without summary embedding", async () => {
    const putResult = await callTool(tools, "wp_blueprint_put", {
      project_id: tmpDir,
      slug: "structured-trust-round-trip",
      document: {
        ...document,
        title: "Structured Trust Round Trip",
        summary: "No embedded dossier markdown here.",
        trust_dossier: trustDossier,
      },
    });
    const putData = parseResult(putResult) as { path: string };
    const draft = readFileSync(putData.path, "utf8");
    expect(draft).toContain("## Summary\n\nNo embedded dossier markdown here.");
    expect(draft).toContain("## Trust Dossier");

    const promoteResult = await callTool(tools, "wp_blueprint_promote", {
      project_id: tmpDir,
      slug: "structured-trust-round-trip",
      to_state: "planned",
    });
    const promoteData = parseResult<{ to_state: string; new_path: string; failures: string[] }>(
      promoteResult,
    );

    expect(promoteResult.isError).toStrictEqual(false);
    expect(promoteData.to_state).toBe("planned");
    expect(promoteData.failures).toStrictEqual([]);
    expect(promoteData.new_path).toContain(path.join("blueprints", "planned"));
    expect(readFileSync(promoteData.new_path, "utf8")).toContain("pass at ");
  });

  it("writes markdown from structured input and returns revision metadata", async () => {
    writeBlueprintReadme(tmpDir);
    const result = await callTool(tools, "wp_blueprint_put", {
      project_id: tmpDir,
      slug: "structured-put-blueprint",
      document,
    });
    const data = parseResult(result) as {
      slug: string;
      path: string;
      status: string;
      content_hash: string;
      revision: string;
      failures: string[];
    };

    expect(result.isError).toStrictEqual(false);
    expect(data.slug).toBe("structured-put-blueprint");
    expect(data.status).toBe("draft");
    expect(data.content_hash).toBeTruthy();
    expect(data.revision).toBe(data.content_hash);
    expect(existsSync(data.path)).toBe(true);
    const written = readFileSync(data.path, "utf8");
    expect(written).toContain("## Product wedge anchor");
    expect(written).toContain("## Summary");
    expect(written).toContain("#### Task 1.1: Write the first structured task");
    expect(data.failures).toStrictEqual([]);
    const readmeText = readFileSync(path.join(tmpDir, "blueprints", "README.md"), "utf8");
    expect(readmeText).toContain("Keep this prose.");
    expect(readmeText).not.toContain("BEGIN: blueprint-index");
  });

  it("replaces an existing blueprint deterministically and re-ingests the new content hash", async () => {
    const first = await callTool(tools, "wp_blueprint_put", {
      project_id: tmpDir,
      slug: "structured-put-blueprint",
      document,
    });
    const firstData = parseResult(first) as { content_hash: string; path: string };

    const second = await callTool(tools, "wp_blueprint_put", {
      project_id: tmpDir,
      slug: "structured-put-blueprint",
      document: {
        ...document,
        summary: "Blueprint used to test deterministic replacement.",
      },
    });
    const secondData = parseResult(second) as { content_hash: string; path: string };

    expect(second.isError).toStrictEqual(false);
    expect(secondData.content_hash).not.toBe(firstData.content_hash);
    expect(readFileSync(secondData.path, "utf8")).toContain(
      "Blueprint used to test deterministic replacement.",
    );

    const getResult = await callTool(tools, "wp_blueprint_get", {
      project_id: tmpDir,
      slug: "structured-put-blueprint",
    });
    const getData = parseResult(getResult) as { content_hash: string };
    expect(getData.content_hash).toBe(secondData.content_hash);
  });

  it("refuses to rewrite executable-state blueprints through the draft-only put surface", async () => {
    const overviewPath = path.join(
      tmpDir,
      "blueprints",
      "planned",
      "structured-put-blueprint",
      "_overview.md",
    );
    mkdirSync(path.dirname(overviewPath), { recursive: true });
    const sentinel = "Existing planned blueprint with a trust dossier sentinel.";
    writeFileSync(
      overviewPath,
      [
        "---",
        "type: blueprint",
        "title: Structured Put Blueprint",
        "status: planned",
        "complexity: 'S'",
        "owner: tester",
        "created: '2026-05-29'",
        "last_updated: '2026-05-29'",
        "---",
        "",
        "# Structured Put Blueprint",
        "",
        sentinel,
        "",
      ].join("\n"),
      "utf8",
    );

    const result = await callTool(tools, "wp_blueprint_put", {
      project_id: tmpDir,
      slug: "structured-put-blueprint",
      document: {
        ...document,
        status: "planned",
        summary: "Attempted executable-state rewrite.",
      },
    });

    expect(result.isError).toStrictEqual(true);
    expect(result.content[0]?.text).toMatch(/only writes draft blueprints/i);
    expect(readFileSync(overviewPath, "utf8")).toContain(sentinel);
    expect(readFileSync(overviewPath, "utf8")).not.toContain("Attempted executable-state rewrite");
  });

  it("returns validation error when required structured fields are missing", async () => {
    const result = await callTool(tools, "wp_blueprint_put", {
      project_id: tmpDir,
      slug: "structured-put-blueprint",
      document: {
        title: "Broken Blueprint",
      },
    });

    expect(result.isError).toStrictEqual(true);
  });
});
