export const gstackPackageMetadata = {
  packageName: '@repo/gstack',
  publishable: false,
  stagedSkillNames: [
    'claude',
    'codex',
    'opencode-go',
    'deepseek',
    'glm',
    'kimi',
    'minimax',
    'mimo',
    'qwen',
    'hy3',
    'plan-eng-review',
    'plan-ceo-review',
    'plan-design-review',
    'review',
  ],
  provenanceRequired: true,
} as const
